import type { Metadata } from "next";
import NAV from "../components/nav";
import "./globals.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NAV/>
        {children}
      </body>
    </html>
  );
}
